### ISSUE TITLE
Could not find a declaration file for module 'react-mapbox-gl-cluster'. 

### ISSUE THREAD

**Issue by RicardoBrito1938** [thuanmb/react-mapbox-gl-cluster#17]
hello team, i am currently using typescript in project, 

when i try to import is shows the following error 

Could not find a declaration file for module 'react-mapbox-gl-cluster'. '/home/ricardo/Documentos/perfectflight/pf-new-frontend/node_modules/react-mapbox-gl-cluster/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-mapbox-gl-cluster` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-mapbox-gl-cluster';`ts(7016)

i tried to declared a file.d.ts, but had no success, would you have any suggestion?

**Comment by thuanmb** [comment]
Hi, sorry for late response. Can you make a small reproducible repos, and write down a step to build and run the sample? so that i can debug the issue. Thanks!

**Comment by orangecoloured** [comment]
The way to repro this is to use the package in any TS project.
The lib simply doesn't have typing.

**Comment by thuanmb** [comment]
I am checking and fixing it.

**Comment by thuanmb** [comment]
Should be fixed at 1.13.0, please help to check if it works!

**Comment by gfabiola** [comment]
@thuanmb I am using 1.15.0 and the type definitions file listed in the package.json does not exist under dist. 

`"types": "dist/types/index.d.ts",`

**Comment by thuanmb** [comment]
@gfabiola Fixed at `94b57ebfd8e16823254c872c7e4f5e080ac3e1db`
