### ISSUE TITLE
Dynamic data source

### ISSUE THREAD

**Issue by JohannLesacher** [thuanmb/react-mapbox-gl-cluster#18]
Hi,

I have a map with filters to conditionnaly render Markers based on user input.
I tried to use this package to cluster some of those markers but even if the data prop on ReactMapboxGlCluster is updated the markers are not.
I'm not using any custom component for now, I only pass the data props to ReactMalboxCluster.

Is this package intended only for static markers ?
Thanks

**Comment by thuanmb** [comment]
The markers should be updated on props change. They are not static markers. Please help to debug to ensure that the state of the markers has changed on props change (by using custom marker component).

**Comment by JohannLesacher** [comment]
Hi ! I did check and the props where changing but I had no time to debug further, I went the custom route by using supercluster to manually create clusters without your package.
Thanks for your answer and have a good day
