### ISSUE TITLE
Error when run project

### ISSUE THREAD

**Issue by ferrari-tran** [thuanmb/react-mapbox-gl-cluster#19]
`./node_modules/react-mapbox-gl-cluster/node_modules/react-mapbox-gl-spiderifier/dist/components/MappedComponent.js
Module not found: Can't resolve '/Users/thuanbui/source_code/react-mapbox-gl-spiderifier/node_modules/@babel/runtime/helpers/esm/classCallCheck' in '/Users/laoton/Workspaces/Study/mapbox-cluster/node_modules/react-mapbox-gl-cluster/node_modules/react-mapbox-gl-spiderifier/dist/components'`

Did you build it again? I saw your computer's name here

**Comment by thuanmb** [comment]
Which version are you running? I cannot reproduce your issue. Can you share a reproducible repo?

**Comment by thuanmb** [comment]
Because the issue's creator has not responded for more than 6 months, closing the the issue as "won't fix". Please help to reopen it when you have any update @ferrari-tran!
Thanks!
