### ISSUE TITLE
renderPopup not defined

### ISSUE THREAD

**Issue by tbiinfotech** [thuanmb/react-mapbox-gl-cluster#2]
I have set the code and getting cluster on map, but when I click, then I am not getting renderPopup() method in code.
Also can we change icons i.e. replace circle with icons as markers?

**Comment by thuanmb** [comment]
hi @tbiinfotech , for `renderPopup`, it's just an example of the showing popup `onClick` event. I updated README for use the console log instead. You should implement `renderPopup` for yourself.

To showing the different icon than circle. You can simple use override the CSS class `.spiderifier-marker-content` with whatever icon you want to.

I will try to add an property for more icon customization later thanks!
