### ISSUE TITLE
Support for react-map-gl

### ISSUE THREAD

**Issue by winston-bosan** [thuanmb/react-mapbox-gl-cluster#3]
Hello thuanmb! Awesome project. Has you got any plan to make it compatible with react-map-gl, the other mapbox react wrapper that is just as popular as react-mapbox-gl?

**Comment by thuanmb** [comment]
@winston-bosan I work on that and update with you later. Thanks!

**Comment by thuanmb** [comment]
After checked the `react-map-gl` there are many issue which I need to resolve and seem it is out of scope of this package. One of the big issue that is `react-map-gl` don't have cluster layer which is the required component for `react-mapbox-gl-cluster`. 

If you're using `deck.gl` layers together with `react-map-gl`, my suggestion for your case is: change to use `react-mapbox-gl` as the top layer. Then using the `deck.gl` layers as the child of `react-mapbox-gl` map. I am doing the same for some project already. Let me know if you need help or advice. Thanks a lots!
