### ISSUE TITLE
Can I change the color of clicked feature of cluster?

### ISSUE THREAD

**Issue by tbiinfotech** [thuanmb/react-mapbox-gl-cluster#4]
Here is my code below:
`<ReactMapboxGlCluster data={data} {...this.getEventHandlers()} />`

On click I am doing:

```
getEventHandlers() {
	    return {
		    onClick: (properties, coords, offset) =>
		    this.renderPopup(properties)
	    };
	}
```

Can I change the color of specific node or point on click of that specifically?

**Comment by thuanmb** [comment]
@tbiinfotech it's duplicating with https://github.com/thuanmb/react-mapbox-gl-cluster/issues/6.

I am closing this issue and will work on the spiderifier customization later.
