### ISSUE TITLE
Seems pointClassName , pointStyles , and clusterClassName  are not working

### ISSUE THREAD

**Issue by tbiinfotech** [thuanmb/react-mapbox-gl-cluster#5]
In my data object I am passing the values of pointClassName , pointStyles , and clusterClassName, but seems that these are not working there.

Actually I want to give id to each node point of cluster.

here is my code:
                               ```
```
{
			      	"type": "Feature",
			      	"properties": {
			      		channel_id: mapchannelslisting[i].channel_id,
			      		location: mapchannelslisting[i].location,
			      		news_source: mapchannelslisting[i].news_source,
			      		language: mapchannelslisting[i].language,
			      		image: 'http://localhost:5000/'+mapchannelslisting[i].image,
			      		latlng: coordinates,
			      		hls_addr: mapchannelslisting[i].hls_addr
			      	},
			      	"geometry": {
				        "type": "Point",
				        "coordinates":coordinates
			      	},
			      	pointClassName:"ccc",
			      	clusterClassName : "clusterClass",
			      	pointStyles : {
			      		class: "pointClass"
			      	}
```
Am I using it wrong , if yes then please correct me.

Thank you!

**Comment by thuanmb** [comment]
@tbiinfotech it's working from my side. For example:
```
      <div className="App">
        <Map {...mapProps} onStyleLoad={this.onStyleLoad}>
          <ReactMapboxGlCluster data={data} {...this.getEventHandlers()} pointClassName="something-for-point" />
        </Map>
      </div>
```
and it result: 
```
<div class="mapboxgl-marker undefined mapboxgl-marker-anchor-center" style="transform: translate(-50%, -50%) translate(462px, 248px);"><div class="nio-marker-content f-width f-height"><div class="cluster-layer--point something-for-point"></div></div></div>
```
Do you mean the custom classname for the spiderifier points instead? If so it's duplicating with https://github.com/thuanmb/react-mapbox-gl-cluster/issues/6.

I am closing this issue and will work on the spiderifier customization later.
